--CMod Advanced Solar -> 5Dim Power
--CMod Elite Solar -> 5Dim Power
--CMod Ultimate Solar -> 5Dim Power
--CMod Advanced Accumulator -> 5Dim Power
--CMod Elite Accumulator -> 5Dim Power
--CMod Ultimate Accumulator -> 5Dim Power
--CMod 