--GDIW Basic Oil Processing (NR) -> 5Dim Liquids
--GDIW Advanced Oil Processing (RR) -> 5Dim Liquids
--GDIW Advanced Oil Processing (NR) -> 5Dim Liquids
--GDIW Advanced Oil Processing (RN) -> 5Dim Liquids
--GDIW Heavy Oil Cracking to Light Oil (R) -> 5Dim Liquids
--GDIW Light Oil Cracking to Petroleum Gas (R) -> 5Dim Liquids