table.insert(data.raw.technology["logistics"].effects,{type = "unlock-recipe", recipe = "cm-mk1-transport-belt-to-ground-30"})
table.insert(data.raw.technology["logistics"].effects,{type = "unlock-recipe", recipe = "cm-mk1-transport-belt-to-ground-50"})
table.insert(data.raw.technology["logistics"].effects,{type = "unlock-recipe", recipe = "cm-pipe-to-ground-mk1-30"})
table.insert(data.raw.technology["logistics"].effects,{type = "unlock-recipe", recipe = "cm-pipe-to-ground-mk1-50"})
table.insert(data.raw.technology["logistics-2"].effects,{type = "unlock-recipe", recipe = "cm-mk2-transport-belt-to-ground-30"})
table.insert(data.raw.technology["logistics-2"].effects,{type = "unlock-recipe", recipe = "cm-mk2-transport-belt-to-ground-50"})
table.insert(data.raw.technology["logistics-3"].effects,{type = "unlock-recipe", recipe = "cm-mk3-transport-belt-to-ground-30"})
table.insert(data.raw.technology["logistics-3"].effects,{type = "unlock-recipe", recipe = "cm-mk3-transport-belt-to-ground-50"})